name: formatting_check
run-name: Check code formatting
on: [push, pull_request]
jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo gem install mdl
          python -m pip install --upgrade pip ruff
      - name: Check lint
        run: ruff check bdfr tests
      - name: Check formatting
        run: ruff format --check bdfr tests
      - name: Check markdown
        run: mdl README.md docs/
